### ISSUE TITLE
Better explanation in Readme / Doc

### ISSUE THREAD

**Issue by markmaas** [withmethod/terraform-aws-efs#2]
Regarding: https://github.com/withmethod/terraform-aws-efs/blob/9049f4b7280c2b4d519f8f5c54e49f84541360a1/variables-local.tf#L8

I think I kinda understand, but would love to see documentation about this feature somewhere?

**Comment by ksatirli** [comment]
Good catch! It was moderately obvious to me while building it, but I do see a need for better explanation.

I'll add it to #1

**Comment by ksatirli** [comment]
Now tracking this in #1
